[package]
name = "first-phase"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
sha2 = "0.10"
sled = "0.34"
data-encoding = "2.3"
num-bigint = "0.4"
